FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY style.css /usr/share/nginx/html/style.css
COPY app.js /usr/share/nginx/html/app.js
COPY dashboard-data.js /usr/share/nginx/html/dashboard-data.js
EXPOSE 80